### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by LilDinker** [s3xysteak/cesium-use#1]
Hello. I am trying to follow the documentation to just get started, specifically just trying to [initialize a viewer](https://s3xysteak.github.io/cesium-use/composables/useViewer.html). When I tried to just use `useViewer()`, like the base example on the [home page](https://s3xysteak.github.io/cesium-use/intro.html) (literally copy pasted the code), I got the following error:

```
cesium-use.js?v=deacfa28:646 Uncaught Error: [cesium-use] Failed to get viewer because viewer is undefined now.
    at j (cesium-use.js?v=deacfa28:646:9)
    at throw-error (cesium-use.js?v=deacfa28:656:27)
    at P (cesium-use.js?v=deacfa28:662:19)
    at setup (App.vue:7:16)
    at callWithErrorHandling (chunk-YYVLN2RI.js?v=da939739:1678:19)
    at setupStatefulComponent (chunk-YYVLN2RI.js?v=da939739:9158:25)
    at setupComponent (chunk-YYVLN2RI.js?v=da939739:9119:36)
    at mountComponent (chunk-YYVLN2RI.js?v=da939739:6335:7)
    at processComponent (chunk-YYVLN2RI.js?v=da939739:6301:9)
    at patch (chunk-YYVLN2RI.js?v=da939739:5817:11)
```

So, I went to the `useViewer()` documentation and tried to use it the same way with the correct imports, as follows:

```
<script setup>
import {ref} from 'vue';
import * as Cesium from 'cesium'
import { Located } from 'cesium-use'

const container = ref(null)

const { isMounted } = useViewerProvider(() => {
  const viewer = new Cesium.Viewer(container)
  // ...
  return viewer
})
</script>

<template>
  <div ref="container" />
  <div>
    <slot v-if="isMounted" />
  </div>
</template>
```

This led me to this error in the console:

```
TypeError: container.appendChild is not a function
    at new Viewer (chunk-5BTTIXEP.js?v=da939739:250604:13)
    at App.vue:9:18
    at cesium-use.js?v=deacfa28:669:15
    at chunk-YYVLN2RI.js?v=da939739:3015:40
    at callWithErrorHandling (chunk-YYVLN2RI.js?v=da939739:1678:19)
    at callWithAsyncErrorHandling (chunk-YYVLN2RI.js?v=da939739:1685:17)
    at hook.__weh.hook.__weh (chunk-YYVLN2RI.js?v=da939739:2995:19)
    at flushPostFlushCbs (chunk-YYVLN2RI.js?v=da939739:1861:32)
    at render2 (chunk-YYVLN2RI.js?v=da939739:7117:7)
    at mount (chunk-YYVLN2RI.js?v=da939739:4108:13)
```

What am I missing? Can't seem to figure this one out so far. Thanks!

**Comment by s3xysteak** [comment]
This is a poor documentation and typo.
```js
const container = ref(null)

const { isMounted } = useViewerProvider(() => {
  const viewer = new Cesium.Viewer(container.value)
  // ...
  return viewer
})
```
`Cesium.Viewer` is a native method of CesiumJS which should receive a `html` instead of a `Ref`.

The document should be checked totally I think.

**Comment by s3xysteak** [comment]
I improved the document and add a [online example](https://stackblitz.com/edit/vitejs-vite-t6qklc?file=src%2FComp.vue).

If you have any more questions, feel free to reopen the issue!

**Comment by LilDinker** [comment]
Good morning. Thanks for the quick response. I am trying to run your example now, and running into some new issues. Here is my `App.vue`:

```
<script setup>
import { ref } from "vue";
import Comp from './components/Comp.vue';
import * as Cesium from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";

const container = ref(null);
Cesium.Ion.defaultAccessToken = // Token

const { isMounted } = useViewerProvider(() => new Cesium.Viewer(container.value));
</script>

<template>
  <div style="height: 100vh" ref="container" />
  <Comp v-if="isMounted" />
</template>

<style>
html,
body,
#app {
  height: 100%;
  margin: 0;
  padding: 0;
}
</style>
```

and here is my `./components/Comp.vue`:

```
<script setup>
import { ref, shallowRef } from "vue";
import * as Cesium from "cesium";
import { Located } from "cesium-use";

const viewer = useViewer();

const show = ref(true);
const pos = shallowRef();

const eventHandler = useEventHandler();
eventHandler(({ position }) => {
  pos.value = viewer.scene.pickPosition(position);
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
</script>

<template>
  <Located v-model="show" :coordinate="pos">
    <div style="background-color: #fff">I am Cesium Use!</div>
  </Located>
</template>
```

The first error thrown in the console is:

`Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

Followed by:
```
VM995:1 Uncaught (in promise) 
SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at chunk-5BTTIXEP.js?v=72fca28c:13441:17
```

Have you run into this before?

**Comment by s3xysteak** [comment]
> Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

As I known, it may be a issue about Browser, which sometimes happened in Microsoft Edge. Usually you can use Chrome to avoid this. But it will not cause any fatal error, so you can just ignore it I think.



> VM995:1 Uncaught (in promise) 
> SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
>     at JSON.parse (<anonymous>)
>     at chunk-5BTTIXEP.js?v=72fca28c:13441:17

Because you can not just run CesiumJS on Vite like that. You can check more information on CesiumJS official website, about how to run CesiumJS with Vite.

Or use the plugin [vite-plugin-cesium-build](https://github.com/s3xysteak/vite-plugin-cesium-build) to run cesium app out-of-the-box!
